### ISSUE TITLE
gettext says: "locales: must set one or more locales"

### ISSUE THREAD

**Issue by mreinsch** [grosser/gettext_i18n_rails#112]
Trying to get gettext_i18n_rails installed on a new project, I'm seeing the following when running rake:

```
rake -T
rake aborted!
invalid configurations:
locales: must set one or more locales
/Users/mr/.rvm/gems/ruby-1.9.3-p448@sple/gems/gettext-3.0.2/lib/gettext/tools/task.rb:229:in `validate'
/Users/mr/.rvm/gems/ruby-1.9.3-p448@sple/gems/gettext-3.0.2/lib/gettext/tools/task.rb:165:in `define'
/Users/mr/.rvm/gems/ruby-1.9.3-p448@sple/gems/gettext-3.0.2/lib/gettext/tools/task.rb:74:in `define'
/Users/mr/.rvm/gems/ruby-1.9.3-p448@sple/gems/gettext_i18n_rails-1.0.1/lib/gettext_i18n_rails/tasks.rb:25:in `block in <top (required)>'
/Users/mr/.rvm/gems/ruby-1.9.3-p448@sple/gems/gettext_i18n_rails-1.0.1/lib/gettext_i18n_rails/tasks.rb:4:in `<top (required)>'
/Users/mr/.rvm/gems/ruby-1.9.3-p448@sple/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
/Users/mr/.rvm/gems/ruby-1.9.3-p448@sple/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `block in require'
/Users/mr/.rvm/gems/ruby-1.9.3-p448@sple/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/mr/.rvm/gems/ruby-1.9.3-p448@sple/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
/Users/mr/.rvm/gems/ruby-1.9.3-p448@sple/gems/gettext_i18n_rails-1.0.1/lib/gettext_i18n_rails/railtie.rb:11:in `block in <class:Railtie>'
/Users/mr/.rvm/gems/ruby-1.9.3-p448@sple/gems/railties-3.2.13/lib/rails/railtie.rb:184:in `instance_exec'
/Users/mr/.rvm/gems/ruby-1.9.3-p448@sple/gems/railties-3.2.13/lib/rails/railtie.rb:184:in `block in load_tasks'
/Users/mr/.rvm/gems/ruby-1.9.3-p448@sple/gems/railties-3.2.13/lib/rails/railtie.rb:184:in `each'
/Users/mr/.rvm/gems/ruby-1.9.3-p448@sple/gems/railties-3.2.13/lib/rails/railtie.rb:184:in `load_tasks'
/Users/mr/.rvm/gems/ruby-1.9.3-p448@sple/gems/railties-3.2.13/lib/rails/engine.rb:423:in `block in load_tasks'
/Users/mr/.rvm/gems/ruby-1.9.3-p448@sple/gems/railties-3.2.13/lib/rails/application/railties.rb:8:in `each'
/Users/mr/.rvm/gems/ruby-1.9.3-p448@sple/gems/railties-3.2.13/lib/rails/application/railties.rb:8:in `all'
/Users/mr/.rvm/gems/ruby-1.9.3-p448@sple/gems/railties-3.2.13/lib/rails/engine.rb:423:in `load_tasks'
/Users/mr/.rvm/gems/ruby-1.9.3-p448@sple/gems/railties-3.2.13/lib/rails/application.rb:145:in `load_tasks'
/Users/mr/.rvm/gems/ruby-1.9.3-p448@sple/gems/railties-3.2.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
/Users/mr/Projects/xxx/yyy/Rakefile:7:in `<top (required)>'
```

I'm at a loss why this happens, looks fine for our existing projects.

**Comment by neohunter** [comment]
It's locales or locale? rails come with locale.

Also, while running the `rake gettext:add_language[es]` i get the error...

**Comment by grosser** [comment]
can you post the backtrace ? (run with --trace)
maybe it's complaining that not even english is set up ?
