### ISSUE TITLE
Does not work well with Ruby 2.4.1

### ISSUE THREAD

**Issue by Qqwy** [grosser/gettext_i18n_rails#167]
I have a Rails 5 project, and I was running Ruby 2.4.1.

When attempting to run the task to set up gettext, I get the following stacktrace:

```
LANGUAGE=nl rails gettext:add_language --trace
** Invoke gettext:add_language (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute gettext:add_language
mkdir -p /home/myusername/Programming/Work/projectname/locale/nl
** Invoke gettext:find (first_time)
** Invoke gettext:setup (first_time)
** Invoke environment 
** Execute gettext:setup
** Execute gettext:find
** Invoke gettext:po:update (first_time)
** Invoke gettext:po:nl:update (first_time)
** Invoke /home/myusername/Programming/Work/projectname/locale/nl/app.po (first_time)
** Invoke /home/myusername/Programming/Work/projectname/locale/nl/app.edit.po (first_time)
** Invoke /home/myusername/Programming/Work/projectname/locale/app.pot (first_time)
** Invoke app/helpers/admin/vacancy_categories_helper.rb (first_time, not_needed)
** Invoke app/helpers/admin/base_helper.rb (first_time, not_needed)
** Invoke app/helpers/admin/users_helper.rb (first_time, not_needed)
** Invoke app/helpers/admin/vacancies_helper.rb (first_time, not_needed)
** Invoke app/helpers/admin/announcements_helper.rb (first_time, not_needed)
** Invoke app/helpers/admin/companies_helper.rb (first_time, not_needed)
** Invoke app/helpers/devise_bootstrap_views_helper.rb (first_time, not_needed)
** Invoke app/helpers/portal_helper.rb (first_time, not_needed)
** Invoke app/helpers/application_helper.rb (first_time, not_needed)
** Invoke app/helpers/vacancies_helper.rb (first_time, not_needed)
** Invoke app/helpers/blogs_helper.rb (first_time, not_needed)
** Invoke app/helpers/profiles_helper.rb (first_time, not_needed)
** Invoke app/helpers/portal_pages_helper.rb (first_time, not_needed)
** Invoke app/helpers/comments_helper.rb (first_time, not_needed)
** Invoke app/helpers/static_pages_helper.rb (first_time, not_needed)
** Invoke app/helpers/companies_helper.rb (first_time, not_needed)
** Invoke app/controllers/concerns/sociable.rb (first_time, not_needed)
** Invoke app/controllers/admin/vacancies_controller.rb (first_time, not_needed)
** Invoke app/controllers/admin/blogs_controller.rb (first_time, not_needed)
** Invoke app/controllers/admin/announcements_controller.rb (first_time, not_needed)
** Invoke app/controllers/admin/base_controller.rb (first_time, not_needed)
** Invoke app/controllers/admin/users_controller.rb (first_time, not_needed)
** Invoke app/controllers/admin/vacancy_categories_controller.rb (first_time, not_needed)
** Invoke app/controllers/admin/companies_controller.rb (first_time, not_needed)
** Invoke app/controllers/vacancies_controller.rb (first_time, not_needed)
** Invoke app/controllers/tinymce_assets_controller.rb (first_time, not_needed)
** Invoke app/controllers/blogs_controller.rb (first_time, not_needed)
** Invoke app/controllers/portal_pages_controller.rb (first_time, not_needed)
** Invoke app/controllers/portal_controller.rb (first_time, not_needed)
** Invoke app/controllers/profiles_controller.rb (first_time, not_needed)
** Invoke app/controllers/application_controller.rb (first_time, not_needed)
** Invoke app/controllers/comments_controller.rb (first_time, not_needed)
** Invoke app/controllers/static_pages_controller.rb (first_time, not_needed)
** Invoke app/controllers/companies_controller.rb (first_time, not_needed)
** Invoke app/models/comment.rb (first_time, not_needed)
** Invoke app/models/vacancy_category.rb (first_time, not_needed)
** Invoke app/models/announcement.rb (first_time, not_needed)
** Invoke app/models/application_record.rb (first_time, not_needed)
** Invoke app/models/blog.rb (first_time, not_needed)
** Invoke app/models/company.rb (first_time, not_needed)
** Invoke app/models/tinymce_upload.rb (first_time, not_needed)
** Invoke app/models/vacancy.rb (first_time, not_needed)
** Invoke app/models/vacancy_vacancy_category.rb (first_time, not_needed)
** Invoke app/models/user.rb (first_time, not_needed)
** Invoke app/jobs/application_job.rb (first_time, not_needed)
** Invoke app/uploaders/feature_image_uploader.rb (first_time, not_needed)
** Invoke app/uploaders/company_logo_uploader.rb (first_time, not_needed)
** Invoke app/uploaders/user_photo_uploader.rb (first_time, not_needed)
** Invoke app/mailers/application_mailer.rb (first_time, not_needed)
** Invoke app/channels/application_cable/connection.rb (first_time, not_needed)
** Invoke app/channels/application_cable/channel.rb (first_time, not_needed)
** Invoke app/views/layouts/mailer.text.haml (first_time, not_needed)
** Invoke app/views/layouts/portal.html.haml (first_time, not_needed)
** Invoke app/views/layouts/admin.html.haml (first_time, not_needed)
** Invoke app/views/layouts/application.html.haml (first_time, not_needed)
** Invoke app/views/layouts/mailer.html.haml (first_time, not_needed)
** Invoke app/views/admin/blogs/_form.html.haml (first_time, not_needed)
** Invoke app/views/admin/blogs/show.html.haml (first_time, not_needed)
** Invoke app/views/admin/blogs/new.html.haml (first_time, not_needed)
** Invoke app/views/admin/blogs/edit.html.haml (first_time, not_needed)
** Invoke app/views/admin/blogs/index.html.haml (first_time, not_needed)
** Invoke app/views/admin/vacancy_categories/_form.html.haml (first_time, not_needed)
** Invoke app/views/admin/vacancy_categories/show.html.haml (first_time, not_needed)
** Invoke app/views/admin/vacancy_categories/new.html.haml (first_time, not_needed)
** Invoke app/views/admin/vacancy_categories/edit.html.haml (first_time, not_needed)
** Invoke app/views/admin/vacancy_categories/index.html.haml (first_time, not_needed)
** Invoke app/views/admin/users/show.html.haml (first_time, not_needed)
** Invoke app/views/admin/users/_table.html.haml (first_time, not_needed)
** Invoke app/views/admin/users/edit.html.haml (first_time, not_needed)
** Invoke app/views/admin/users/index.html.haml (first_time, not_needed)
** Invoke app/views/admin/users/unapproved.html.haml (first_time, not_needed)
** Invoke app/views/admin/vacancies/_form.html.haml (first_time, not_needed)
** Invoke app/views/admin/vacancies/show.html.haml (first_time, not_needed)
** Invoke app/views/admin/vacancies/new.html.haml (first_time, not_needed)
** Invoke app/views/admin/vacancies/edit.html.haml (first_time, not_needed)
** Invoke app/views/admin/vacancies/index.html.haml (first_time, not_needed)
** Invoke app/views/admin/companies/_form.html.haml (first_time, not_needed)
** Invoke app/views/admin/companies/show.html.haml (first_time, not_needed)
** Invoke app/views/admin/companies/new.html.haml (first_time, not_needed)
** Invoke app/views/admin/companies/edit.html.haml (first_time, not_needed)
** Invoke app/views/admin/companies/index.html.haml (first_time, not_needed)
** Invoke app/views/admin/base/index.html.haml (first_time, not_needed)
** Invoke app/views/admin/announcements/show.html.haml (first_time, not_needed)
** Invoke app/views/admin/announcements/_form.haml (first_time, not_needed)
** Invoke app/views/admin/announcements/new.html.haml (first_time, not_needed)
** Invoke app/views/admin/announcements/edit.html.haml (first_time, not_needed)
** Invoke app/views/admin/announcements/index.html.haml (first_time, not_needed)
** Invoke app/views/blogs/_form.html.haml (first_time, not_needed)
** Invoke app/views/blogs/show.html.haml (first_time, not_needed)
** Invoke app/views/blogs/new.html.haml (first_time, not_needed)
** Invoke app/views/blogs/edit.html.haml (first_time, not_needed)
** Invoke app/views/blogs/index.html.haml (first_time, not_needed)
** Invoke app/views/profiles/edit.html.haml (first_time, not_needed)
** Invoke app/views/vacancies/show.html.haml (first_time, not_needed)
** Invoke app/views/vacancies/index.html.haml (first_time, not_needed)
** Invoke app/views/comments/_form.html.haml (first_time, not_needed)
** Invoke app/views/comments/show.html.haml (first_time, not_needed)
** Invoke app/views/comments/new.html.haml (first_time, not_needed)
** Invoke app/views/comments/edit.html.haml (first_time, not_needed)
** Invoke app/views/comments/index.html.haml (first_time, not_needed)
** Invoke app/views/companies/show.html.haml (first_time, not_needed)
** Invoke app/views/companies/index.html.haml (first_time, not_needed)
** Invoke app/views/devise/confirmations/new.html.haml (first_time, not_needed)
** Invoke app/views/devise/registrations/new.html.haml (first_time, not_needed)
** Invoke app/views/devise/registrations/edit.html.haml (first_time, not_needed)
** Invoke app/views/devise/mailer/reset_password_instructions.html.haml (first_time, not_needed)
** Invoke app/views/devise/mailer/unlock_instructions.html.haml (first_time, not_needed)
** Invoke app/views/devise/mailer/confirmation_instructions.html.haml (first_time, not_needed)
** Invoke app/views/devise/unlocks/new.html.haml (first_time, not_needed)
** Invoke app/views/devise/shared/_links.html.haml (first_time, not_needed)
** Invoke app/views/devise/passwords/new.html.haml (first_time, not_needed)
** Invoke app/views/devise/passwords/edit.html.haml (first_time, not_needed)
** Invoke app/views/devise/sessions/new.html.haml (first_time, not_needed)
** Invoke app/views/static_pages/home.html.haml (first_time, not_needed)
** Invoke app/views/portal_pages/home.html.haml (first_time, not_needed)
** Invoke app/views/shared/_comments_section.html.haml (first_time, not_needed)
** Invoke config/environment.rb (first_time, not_needed)
** Invoke config/deploy/staging.rb (first_time, not_needed)
** Invoke config/deploy/production.rb (first_time, not_needed)
** Invoke config/environments/staging.rb (first_time, not_needed)
** Invoke config/environments/test.rb (first_time, not_needed)
** Invoke config/environments/production.rb (first_time, not_needed)
** Invoke config/environments/development.rb (first_time, not_needed)
** Invoke config/initializers/application_controller_renderer.rb (first_time, not_needed)
** Invoke config/initializers/backtrace_silencers.rb (first_time, not_needed)
** Invoke config/initializers/new_framework_defaults.rb (first_time, not_needed)
** Invoke config/initializers/inflections.rb (first_time, not_needed)
** Invoke config/initializers/session_store.rb (first_time, not_needed)
** Invoke config/initializers/cookies_serializer.rb (first_time, not_needed)
** Invoke config/initializers/wrap_parameters.rb (first_time, not_needed)
** Invoke config/initializers/assets.rb (first_time, not_needed)
** Invoke config/initializers/filter_parameter_logging.rb (first_time, not_needed)
** Invoke config/initializers/devise.rb (first_time, not_needed)
** Invoke config/initializers/carrierwave.rb (first_time, not_needed)
** Invoke config/initializers/mime_types.rb (first_time, not_needed)
** Invoke config/puma.rb (first_time, not_needed)
** Invoke config/application.rb (first_time, not_needed)
** Invoke config/boot.rb (first_time, not_needed)
** Invoke config/routes.rb (first_time, not_needed)
** Invoke config/spring.rb (first_time, not_needed)
** Invoke config/deploy.rb (first_time, not_needed)
** Execute /home/myusername/Programming/Work/projectname/locale/app.pot
Error parsing app/views/layouts/mailer.text.haml
rails aborted!
unrecognized RUBY_VERSION 2.4.1
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/ruby_parser-3.8.4/lib/ruby_parser_extras.rb:1504:in `for_current_ruby'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/gettext_i18n_rails-1.8.0/lib/gettext_i18n_rails/ruby_gettext_extractor.rb:15:in `parse_string'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/gettext_i18n_rails-1.8.0/lib/gettext_i18n_rails/base_parser.rb:12:in `parse'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/gettext-3.2.2/lib/gettext/tools/xgettext.rb:365:in `block in parse_path'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/gettext-3.2.2/lib/gettext/tools/xgettext.rb:360:in `each'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/gettext-3.2.2/lib/gettext/tools/xgettext.rb:360:in `parse_path'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/gettext-3.2.2/lib/gettext/tools/xgettext.rb:168:in `block in parse'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/gettext-3.2.2/lib/gettext/tools/xgettext.rb:166:in `each'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/gettext-3.2.2/lib/gettext/tools/xgettext.rb:166:in `parse'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/gettext-3.2.2/lib/gettext/tools/xgettext.rb:217:in `generate_pot'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/gettext-3.2.2/lib/gettext/tools/xgettext.rb:151:in `run'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/gettext-3.2.2/lib/gettext/tools/xgettext.rb:34:in `run'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/gettext-3.2.2/lib/gettext/tools/task.rb:330:in `xgettext'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/gettext-3.2.2/lib/gettext/tools/task.rb:314:in `create_pot'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/gettext-3.2.2/lib/gettext/tools/task.rb:306:in `block in define_pot_file_task'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:216:in `block in invoke_prerequisites'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `each'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `invoke_prerequisites'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:193:in `block in invoke_with_call_chain'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:216:in `block in invoke_prerequisites'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `each'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `invoke_prerequisites'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:193:in `block in invoke_with_call_chain'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:216:in `block in invoke_prerequisites'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `each'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `invoke_prerequisites'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:193:in `block in invoke_with_call_chain'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:216:in `block in invoke_prerequisites'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `each'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `invoke_prerequisites'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:193:in `block in invoke_with_call_chain'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/gettext_i18n_rails-1.8.0/lib/gettext_i18n_rails/tasks.rb:65:in `block (2 levels) in <top (required)>'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/gettext_i18n_rails-1.8.0/lib/gettext_i18n_rails/tasks.rb:110:in `block (2 levels) in <top (required)>'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
/home/myusername/Programming/Work/projectname/bin/rails:9:in `require'
/home/myusername/Programming/Work/projectname/bin/rails:9:in `<top (required)>'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `load'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `call'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/client/command.rb:7:in `call'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/client.rb:30:in `run'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/spring-2.0.1/bin/spring:49:in `<top (required)>'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `load'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `<top (required)>'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
/home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
/home/myusername/Programming/Work/projectname/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => gettext:po:update => gettext:po:nl:update => /home/myusername/Programming/Work/projectname/locale/nl/app.po => /home/myusername/Programming/Work/projectname/locale/nl/app.edit.po => /home/myusername/Programming/Work/projectname/locale/app.pot
```

Moving back to ruby 2.3.4 makes it work.

I do not know if this is the fault of gettext_i18n_rails or one of its dependencies, but that is something I hope you can help me figure out.

**Comment by grosser** [comment]
error clearly comes from /home/myusername/.asdf/installs/ruby/2.4.1/lib/ruby/gems/2.4.0/gems/ruby_parser-3.8.4/lib/ruby_parser_extras.rb:1504:in `for_current_ruby'
 ... so upgrade or make a issue there
